### ISSUE TITLE
Does this software can be used for P6-C4 chemistry?

### ISSUE THREAD

**Issue by RobinQi** [hacone/AgIn#1]
Sorry to trouble you.
As you know, SMRT Analysis 2.3.0 is not good for 5mC analysis using P6-C4 chemistry. So, I want to know whether your software is ok for P6-C4.
Thank you!

**Comment by hacone** [comment]
Dear Robin Qi,

Yes, SMRT Analysis 2.3 is not designed for 5mC detection with any
polymerase/chemistry currently released. This is because the signals for
5mC is too subtle to detect confidently.
AgIn was tested with P6-C4 and P4-C2 data, and it performed equally well
with both chemistry. Actually, the preprint on bioRxiv is based on P6-C4
data mainly.
When you use P6-C4 (this is now the de facto standard of PacBio data),
please use these parameters:
-b AgIn/resources/P6C4.dat
-g -0.55

I've experienced the situation where these parameters do not performed well
for unknown reason, possibly something to do with how to run SMRT Analysis
to get IPD data. Please be careful when you interpret the results.

Thank you,
Yuta

2016-05-30 15:08 GMT+09:00 Robin Qi notifications@github.com:

**Comment by RobinQi** [comment]
Thank you very much!
