### ISSUE TITLE
How to execute ?

### ISSUE THREAD

**Issue by ebioman** [hacone/AgIn#4]
Hello I got a bit confused by the README. If I try to execute it I receive the following error 

<pre><code>
Error: Could not find or load main class org.codehaus.plexus.classworlds.launcher.Launcher
</code></pre>

Now if I check what it actually executes, I see the following:

```
/software/Development/java_jdk/1.8.0_102/bin/java -classpath AgIn/src/lib/plexus-classworlds-*.jar -Dclassworlds.conf=AgIn/src/bin/classworld.conf -Dproject.home=AgIn/src org.codehaus.plexus.classworlds.launcher.Launcher
```

Now the funny thing is that there is no lib folder in src . Similarly the configuration is not right but is actually located in /AgIn/src/script/classworld.conf 

What am I missing here ?
Cheers

**Comment by hacone** [comment]
Hi, please try this to fix the problem.

In order to run the program, firstly, please compile it as:
$ bin/sbt package-dist

Then dist/ directory will appear.
For analyzing P6/C4 data, please use resources/P6C4.dat as beta, and
-0.55 as gamma, like

``` run.sh

#!/bin/bash

BETA=/path/to/AgIn/resources/P6C4.dat;
GAMMA=-0.55
REF=/path/to/fasta.fa
LEN=40

JVM_OPTS="-Xmx48G" /path/to/AgIn/target/dist/bin/launch \
-f ${REF} \
-i /path/to/modifications.csv \
-o ${REF}_Agin \
-l $LEN -b $BETA \
-c -g $GAMMA \
predict >& agin.predict.log

```

-l option can be safely loosen to 40 (CpGs).
Finally, unexplained option "-c" will give additional output which
describes multi-level prediction.
(To run the demo, please fix the comment-outed line running AgIn.)

Best,

Yuta / hacone

2016-09-14 7:07 GMT-04:00 ebioman notifications@github.com:

**Comment by ebioman** [comment]
Thanks very much for the fast reply. The compiling is not working as it complains about a broken class file

    error: error while loading CharSequence, class file '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.91-3.b14.el6_8.x86_64/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
(bad constant pool tag 18 at byte 10)

I tried different versions of java and received always the same error.
Any thoughts on that ?

**Comment by ebioman** [comment]
Thanks, works well now
