### ISSUE TITLE
Absence of hypermethylated regions

### ISSUE THREAD

**Issue by ebioman** [hacone/AgIn#6]
Hi
Another question, regarding the hypermethylated regions and the decision threshold.
Currently I obtain a gff file together with the wig files.
If I visualize these, I can see a nice correlation between regions with low methylation status (continious levels) and the gff annotation "hypomethylated region". On the other hand I see no "hypermethylated region" annotated. First, I thought that it automatically complements, but that is not the case as we have intermediate methylated regions and regions with too low coverage which are not annotated neither.
So, how can I get an annotation for the hypermethylated regions ?

What I used:

```
Launcher -f longestContig.fasta -i basemods.csv -o longestContig.fasta_Agin_P6C4_binary -l 40 -b /software/AgIn/resources/P6C4.dat  -c -g -0.55 predict
```

**Comment by hacone** [comment]
Hi, since the gff file documents hypomethylated regions based on binary prediction, you are right that hypermethylated regions are complements of reported hypomethylated regions.
CpGs with too low coverage are ignored at the first place, so please note these region might contain such CpGs, but anyway they are not counted in calculation of the size (#CpGs) of the regions.
Ignored CpG sites don't appear in wig file neither, but you can check which CpGs is ignored by visualizing wig in genome browser and compare them with the set of all CpG sites. In UCSC GB, you can do this by showing short match (with "CG").

**Comment by ebioman** [comment]
Thanks, this answered my question.
Cheers
